



CREATE  TABLE ADREÇA(
		ID VARCHAR(10) PRIMARY KEY,
		CARRER VARCHAR(100),
		CIUTAT VARCHAR(70) ,
		COD_POSTAL NUMBER(5),
		PROVINCIA VARCHAR(50),
		PAIS VARCHAR(50)
		
			);




CREATE TABLE FARMACEUTIC(


		ID Number(5) PRIMARY KEY,
		Nombre VARCHAR(50),
		COD_ADDR REFERENCES ADREÇA(ID) UNIQUE
		
		
		
		
);

	
		
			
		CREATE TABLE CLIENT(
		
		ID NUMBER(6) PRIMARY KEY,
		COD_DIR REFERENCES ADREÇA(ID) UNIQUE,
		NOM VARCHAR(50),
		Data_alta DATE,
		num_targeta NUMBER(16),
		cad_targeta DATE
		
		
		
		
					);
				
			
			CREATE TABLE ESTAT_PREESCRIPCIO(
	
						ID NUMBER(2) PRIMARY KEY,
						DESCRIPCIO VARCHAR(50)
				
		
		
		
		);
	
	
	
	CREATE TABLE ESTAT_PAGAMENT (

				ID NUMBER(2) ,
				TOKEN VARCHAR(255),
				
				DESCRIPCIO VARCHAR(50),
				
				CONSTRAINT PK_ESTAT_PAGAMENT PRIMARY KEY (ID,TOKEN)
				
			
	);


	CREATE TABLE COMPANYIA (
							
								ID NUMBER(5) PRIMARY KEY,
								NOM VARCHAR(50),
								TELEFONO VARCHAR(9)
					
					);
			
			
			
			 
			
    
    
    
    
    	CREATE TABLE FARMAC(
							
							ID NUMBER(9) PRIMARY KEY,
							NOM VARCHAR(50),
							ID_COMPANYIA REFERENCES COMPANYIA(ID),
							COST DECIMAL(6,2),
							DATA_LLANÇAMENT DATE,
							ID_FARMAC_GENERIC REFERENCES FARMAC(ID)
							
							);
							
							
	
			
			
		
			
			
		
				
	CREATE TABLE ITEMS_PREESCRIPCIO (

						ID_PREE NUMBER(12),
						ID_FARMAC NUMBER(9),
						QUANTITAT NUMBER(2),
						INSTRUCCIONS VARCHAR(200),
		CONSTRAINT PK_ITEMS_PREESCRIPCIO PRIMARY KEY (ID_PREE,ID_FARMAC)
			
	
						);	
				
					
					
					
							/*LA TABLA PREESCRIPCIO REQUIERE UNA CLAU ALIENA LA CUAL ES COMPOSTA 
							 * I AIXO EM DA ERROR PUES NO ES RECONOCIDO DE NINGUNA MANERA, 
							 * EH INTENTAT AMB CONSTRAINT FK_TOKEN_PREESCRIPCIO FOREING KEY (ID,TOKEN) REFERENCES ESTAT_PAGAMENT(ID,TOKEN) 
							 * PERO NO ES ACEPTAT DEBIDO A QUE NO SON CLAUS PRIMARIES A PESAR DE ESTAR EN EL CONSTRAINT*/				
				
	CREATE TABLE PREESCRIPCIO(
					
					ID NUMBER(12) PRIMARY KEY,
					ID_CLI REFERENCES CLIENT(ID),
					ID_FARM  REFERENCES FARMACEUTIC(ID),
					DATA_PREE DATE,
					ID_ESTAT_PREE REFERENCES ESTAT_PREESCRIPCIO(ID),
					ID
					
					CONSTRAINT ID_TOKEN_PREESCRIPCIO FOREIGN KEY (ID,TOKEN) REFERENCES ESTAT_PAGAMENT(ID,TOKEN)
   					 
					
				);
					
		
					
				
		
				
				
				
				
					
				
				
				
				
				
				